### ISSUE TITLE
.git is included in the npm build

### ISSUE THREAD

**Issue by burrrata** [theturtle32/WebSocket-Node#355]
I often get errors that node_modules/websocket appears to be a git repo or submodule. Then I have to manually go in and remove the .git file. Is there a reason that the .git file is included in the build that npm downloads?

**Comment by ibc** [comment]
Already fixed in master branch. Waiting for a new npm release.

**Comment by CarlosLanderas** [comment]
Still having problems. Have this fix been included in the last release?

**Comment by ibc** [comment]
No, it's not. Unfortunately it seems that @theturtle32 is no longer maintaining this repo :(

**Comment by CarlosLanderas** [comment]
@theturtle32, please just create a new release now that the fix is in the master branch. This is affecting a lot of packages

**Comment by CarlosLanderas** [comment]
@ibc do you know what is the version of the latest package not having this issue to force version in package.json so we don't get affected by packages dependencies?

**Comment by ibc** [comment]
I don't know, sorry. You can try installing different versions and check their content.

**Comment by chaseadam** [comment]
duplicate #353
